theme: jekyll-theme-hacker
title: Build Complete - IT and ProjectManagement consultant
description: We can deliver a broad range of IT and projectmanagement solutions, from web to vision and medico - from implementation to project management